#!/usr/bin/env python3
"""
Regenerates the "Listen & Read" block of index.html:
  - latest podcast episodes, from the Apple Podcasts lookup API
  - latest LinkedIn newsletter articles, scraped from the public newsletter page

Writes the rendered HTML between the CONTENT:START / CONTENT:END markers in
index.html, and dumps the raw data to content.json for debugging.

Usage:  python3 update_content.py [path/to/index.html]
"""

import html
import json
import os
import re
import sys
import urllib.request
from datetime import datetime

APPLE_ID = "1543657106"
APPLE_SHOW = f"https://podcasts.apple.com/us/podcast/the-french-philosopher/id{APPLE_ID}"
NEWSLETTER = "https://www.linkedin.com/newsletters/the-french-philosopher-7216970073071104001/"

N_EPISODES = 3
N_ARTICLES = 3

UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

START = "<!-- CONTENT:START — generated by update_content.py, do not edit by hand -->"
END = "<!-- CONTENT:END -->"


def get(url, timeout=30):
    req = urllib.request.Request(url, headers={
        "User-Agent": UA,
        "Accept-Language": "en-US,en;q=0.9",
    })
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return r.read().decode("utf-8", "replace")


# --------------------------------------------------------------------------- #
# podcast
# --------------------------------------------------------------------------- #

def fetch_episodes(n=N_EPISODES):
    data = json.loads(get(
        f"https://itunes.apple.com/lookup?id={APPLE_ID}"
        f"&entity=podcastEpisode&limit={n + 5}"
    ))
    episodes = []
    for r in data["results"]:
        if r.get("wrapperType") != "podcastEpisode":
            continue
        title = re.sub(r"^\s*\d+[.)]\s*", "", r.get("trackName", "").strip())
        released = r.get("releaseDate", "")[:10]
        ms = r.get("trackTimeMillis") or 0
        episodes.append({
            "title": title,
            "url": r.get("trackViewUrl", "").split("&uo=")[0],
            "date": released,
            "date_label": label_date(released),
            "minutes": round(ms / 60000) if ms else None,
            "blurb": clean(r.get("description") or r.get("shortDescription") or ""),
            "image": (r.get("artworkUrl600")
                      or r.get("artworkUrl160")
                      or r.get("artworkUrl60", "")),
        })
        if len(episodes) == n:
            break
    if not episodes:
        raise RuntimeError("Apple returned no episodes")
    return episodes


# --------------------------------------------------------------------------- #
# newsletter
# --------------------------------------------------------------------------- #

def fetch_articles(n=N_ARTICLES):
    page = get(NEWSLETTER)
    seen, articles = set(), []

    # The public newsletter page renders each issue as an <a href=".../pulse/...">
    # card; the card's text carries the title and a "Published on <date>" line.
    for block in re.split(r'(?=<a[^>]+href="https://www\.linkedin\.com/pulse/)', page):
        m = re.match(r'<a[^>]+href="(https://www\.linkedin\.com/pulse/[^"?]+)', block)
        if not m:
            continue
        url = m.group(1)
        if "lehuger" not in url or url in seen:
            continue
        seen.add(url)

        text = html.unescape(re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", block[:4000]))).strip()
        title = text.split("Stephanie Lehuger")[0].strip(" -–—·|")
        if not title:
            continue

        d = re.search(r"Published on ([A-Z][a-z]{2} \d{1,2}, \d{4})", text)
        iso = ""
        if d:
            try:
                iso = datetime.strptime(d.group(1), "%b %d, %Y").strftime("%Y-%m-%d")
            except ValueError:
                pass

        articles.append({"title": title, "url": url, "date": iso,
                         "date_label": label_date(iso), "image": "", "blurb": ""})
        if len(articles) == n:
            break

    if not articles:
        raise RuntimeError("no articles found on the newsletter page — LinkedIn markup may have changed")

    # Cover image + standfirst come from each article's own Open Graph tags.
    for a in articles:
        try:
            art = get(a["url"])
        except Exception as e:                       # noqa: BLE001
            print(f"  ! {a['url']}: {e}", file=sys.stderr)
            continue
        a["image"] = og(art, "og:image")
        a["blurb"] = clean(og(art, "og:description"))
        t = og(art, "og:title")
        if t:
            a["title"] = t
    return articles


def og(doc, prop):
    m = re.search(rf'<meta[^>]+property="{prop}"[^>]+content="([^"]*)"', doc) \
        or re.search(rf'<meta[^>]+content="([^"]*)"[^>]+property="{prop}"', doc)
    return html.unescape(m.group(1)) if m else ""


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #

# Recurring openers that add nothing on a card, stripped from the excerpt.
BOILERPLATE = [
    r"Hey there,?\s*your philosophy BFF here",
]


def clean(text, limit=150):
    text = html.unescape(re.sub(r"<[^>]+>", " ", text))
    text = re.sub(r"\s+", " ", text).strip()
    for pat in BOILERPLATE:
        text = re.sub(rf"^{pat}\s*[^\w\s]*\s*", "", text, flags=re.I)
    text = text.lstrip(" .!?,:;—-")
    if len(text) <= limit:
        return text
    return text[:limit].rsplit(" ", 1)[0].rstrip(" ,.;:—-") + "…"


def label_date(iso):
    if not iso:
        return ""
    return datetime.strptime(iso, "%Y-%m-%d").strftime("%b %Y").upper()


def e(s):
    return html.escape(s or "", quote=True)


# --------------------------------------------------------------------------- #
# rendering
# --------------------------------------------------------------------------- #

CARD = "display:flex; text-decoration:none; color:#13383B"


def episode_row(ep):
    """Title and excerpt only — no date or duration line."""
    return f'''<a class="card" href="{e(ep['url'])}" target="_blank" rel="noopener" style="{CARD}; flex-direction:column; gap:7px; padding:18px 0; border-top:1px solid #DCE2E4">
                <span class="card-t" style="font-family:'Plus Jakarta Sans'; font-weight:800; font-size:18px; line-height:1.25; letter-spacing:-.01em; max-width:52ch">{e(ep['title'])}</span>
                <span style="font-size:14px; line-height:1.55; color:#3D6467; max-width:62ch">{e(ep['blurb'])}</span>
              </a>'''


def article_card(a):
    """Text only — the LinkedIn cover art does not match the site's style."""
    return f'''<a class="card" href="{e(a['url'])}" target="_blank" rel="noopener" style="{CARD}; flex-direction:column; gap:9px; padding:20px 22px; border-radius:15px; background:#FFFFFF; border:1px solid #DCE2E4">
              <span class="card-t" style="font-family:'Plus Jakarta Sans'; font-weight:800; font-size:17px; line-height:1.25; letter-spacing:-.01em">{e(a['title'])}</span>
              <span style="font-size:13.5px; line-height:1.5; color:#3D6467">{e(a['blurb'])}</span>
            </a>'''


def render(episodes, articles):
    rows = "\n              ".join(episode_row(x) for x in episodes)
    cards = "\n            ".join(article_card(x) for x in articles)
    cover = episodes[0]["image"] if episodes else ""
    return f'''{START}
      <div class="r-pad" id="content" style="padding:52px 56px; background:#FAFBFC; border-top:1px solid #DCE2E4; display:flex; flex-direction:column; gap:44px">

        <div style="display:flex; flex-direction:column; gap:22px">
          <div class="r-row" style="display:flex; align-items:baseline; justify-content:space-between; gap:20px">
            <h2 class="r-h2" style="margin:0; font-family:'Plus Jakarta Sans'; font-weight:800; font-size:38px; line-height:1.05; letter-spacing:-.03em; color:#13383B">Listen to the podcast</h2>
            <a class="linkedin-rec" href="{APPLE_SHOW}" target="_blank" rel="noopener" style="font-size:13px; font-weight:600; color:#3D6467; text-decoration:none; border-bottom:1px solid #DCE2E4; white-space:nowrap">All episodes on Apple Podcasts →</a>
          </div>
          <!-- The cover has a fixed width and stretches to the episode list's
               height, so the two columns always end flush. aspect-ratio cannot
               do this in a flex row: its width would depend on a height that is
               itself derived from the row, and it collapses to zero. -->
          <div class="r-podcast" style="display:flex; gap:44px; align-items:stretch">
            <a class="clip" href="{APPLE_SHOW}" target="_blank" rel="noopener" style="flex:0 0 auto; width:330px; min-height:330px; border-radius:15px; background:#FBEBE0 url({e(cover)}) center/cover no-repeat; box-shadow:0 8px 24px rgba(19,56,59,.14); text-decoration:none"></a>
            <div style="flex:1 1 0; min-width:0; display:flex; flex-direction:column">
              {rows}
            </div>
          </div>
        </div>

        <div style="display:flex; flex-direction:column; gap:22px">
          <div class="r-row" style="display:flex; align-items:baseline; justify-content:space-between; gap:20px">
            <h2 class="r-h2" style="margin:0; font-family:'Plus Jakarta Sans'; font-weight:800; font-size:38px; line-height:1.05; letter-spacing:-.03em; color:#13383B">Read the newsletter</h2>
            <a class="linkedin-rec" href="{NEWSLETTER}" target="_blank" rel="noopener" style="font-size:13px; font-weight:600; color:#3D6467; text-decoration:none; border-bottom:1px solid #DCE2E4; white-space:nowrap">All issues on LinkedIn →</a>
          </div>
          <div class="r-3cards" style="display:grid; grid-template-columns:repeat(3, 1fr); gap:26px">
            {cards}
          </div>
        </div>

      </div>
      {END}'''


# --------------------------------------------------------------------------- #

def main():
    path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "index.html")

    cache_path = os.path.join(os.path.dirname(os.path.abspath(path)), "content.json")
    cache = {}
    if os.path.exists(cache_path):
        with open(cache_path, encoding="utf-8") as f:
            cache = json.load(f)

    def source(name, key, fn):
        """Fetch a source; fall back to the last good result rather than
        wiping a working section when one site is unreachable."""
        print(f"fetching {name}…")
        try:
            items = fn()
        except Exception as exc:                     # noqa: BLE001
            if not cache.get(key):
                raise SystemExit(f"{name} failed and no cached copy exists: {exc}")
            print(f"  ! {exc} — keeping the cached copy", file=sys.stderr)
            return cache[key]
        for x in items:
            print(f"  · {x['date']}  {x['title']}")
        return items

    episodes = source("podcast episodes", "episodes", fetch_episodes)
    articles = source("newsletter articles", "articles", fetch_articles)

    with open(path, encoding="utf-8") as f:
        page = f.read()

    if START not in page or END not in page:
        raise SystemExit(f"markers not found in {path} — add {START} … {END} first")

    block = render(episodes, articles)
    updated = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block,
                     page, flags=re.S)

    if updated == page:
        print("no change")
        return

    with open(path, "w", encoding="utf-8") as f:
        f.write(updated)
    with open(cache_path, "w", encoding="utf-8") as f:
        json.dump({"episodes": episodes, "articles": articles}, f, indent=2, ensure_ascii=False)
    print(f"updated {path}")


if __name__ == "__main__":
    main()
